### ISSUE TITLE
Investigate key-spacing rule in "minimum" mode

### ISSUE THREAD

**Issue by elnaz** [lob/eslint-config-lob#12]
The [current configuration](https://github.com/lob/eslint-config-lob/blob/master/index.js#L28) does not find this spacing to be problematic:

``` js
var foo = {
  a: 'good',
  b : 'bad'
}
```

The [docs](http://eslint.org/docs/rules/key-spacing) are not clear on how mode interacts with `beforeColon` so this may be a bug.

**Comment by robinjoseph08** [comment]
Fixed by #17!
